# Generated by Django 2.2 on 2021-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders', verbose_name='Slider Görseli')),
            ],
            options={
                'verbose_name': 'Slider Görseli',
                'verbose_name_plural': 'Slider Görselleri',
            },
        ),
    ]
